title: Phone Myat Kyaw Thu
logo: photo.jpg
#description
show_downloads: true
theme: jekyll-theme-minimal

sass:
  style: |
    .site-logo img {
      width: 150px; /* Adjust size as needed */
      height: 150px;
      border-radius: 50%;
      display: block;
      margin: 0 auto;
    }

